### PR TITLE
PHP CS Fixer

### PR DESCRIPTION
**Pull request by MichaelGooden**

### CODE REVIEW

**Comment by mostertb** [comment]
I like this.

Please could I ask you to resolve the conflict in the composer.json when  you get a moment

**Comment by MichaelGooden** [comment]
Rebased to resolve merge conflicts as well as included newest CS fixes. Try merge this first before other PRs to avoid further conflicts.

**Comment by MichaelGooden** [comment]
@mostertb Rebased again to resolve new issues and added better testing commands. Overwrote your merge, sorry!

**Comment by mostertb** [comment]
Thanks for this - it makes processing Pull Requests a lot easier

**Pull request merged**
