### PR TITLE
Added OutieDorflingProfle

### PR DESCRIPTION
**Pull request by Dorfling**
PlzGivSticker
kthxbye

### CODE REVIEW

**Comment by mostertb** [comment]
@Dorfling I was experimenting with pushing updates to your PR as you missed something. In the processes it got automatically closed... Sorry

Your changes are one master though. Thanks for the submission

**Comment by Dorfling** [comment]
What did I miss? The tests passed, when I checked.

**Comment by mostertb** [comment]
You  hadn't actually instantiated you profile class in the `Kernel.php`. Its on `Step Four`

Github has added a feature where the maintainer can push to the branch that a PR is made from. This allows the change I make to show up on the PR!

I messed up by fetching your repo and fixing the instantiation, but not pulling the latest commits... so I simply merged your stuff in to the main project's master :)

**Comment by Dorfling** [comment]
Reading. My only weakness.
Thats a really cool feature... I might have some uses for it

On Sep 30, 2018 12:20 PM, "Brad Mostert" <notifications@github.com> wrote:

You hadn't actually instantiated you profile class in the Kernel.php. Its
on Step Four

Github has added a feature where the maintainer can push to the branch that
a PR is made from. This allows the change I make to show up on the PR!

I messed up by fetching your repo and fixing the instantiation, but not
pulling the latest commits... so I simply merged your stuff in to the main
project's master :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mostertb/phpsa-2018-profiles/pull/33#issuecomment-425710336>,
or mute the thread

**Pull request closed without merging**
