### PR TITLE
Update website design

### PR DESCRIPTION
**Pull request by jadonbrownza**

### CODE REVIEW

**Review by MichaelGooden — CHANGES_REQUESTED** [review]
What is your motivation for removing the strict types declaration. It can still affect how the file will be executed, even if it does not have classes itself.

**Review by jadonbrownza — COMMENTED** [review]
You're right, this would still serve a purpose.

**Comment by mostertb** [comment]
Hi @scheMeZa 

This is pretty cool. Did you make the theme or is it "off-the-shelf"? If its the latter, what is the licensing?

Also, I see that you've removed the PHP requirement in the `composer.json`, I want to force PHP7 this year to facilitate the joice of other packages.

Similarly, I dont want to commit a `composer.lock` due to the wide variety of dev environments the attendees are running

**Comment by asgrim** [comment]
> Similarly, I dont want to commit a `composer.lock` due to the wide variety of dev environments the attendees are running

That's really why a `composer.lock` *should* indeed exist... to ensure dependencies are consistent everywhere and different environments don't get different expectations.

**Comment by mostertb** [comment]
@asgrim This is always a great discussion.

I didn't want to exclude 7.0 users because we locked to a package version that requires 7.2 simply because that was the version we did the `composer update` on.  I was hoping to mitigate the *different expectations* with strong version constraints  rather than a lock.

An alternative option for this situation may have been to build the lockfile with the `--prefer-lowest` composer parameter.

Ultimately, the choice of packages we wanted didnt support 7.0 anyway and after I moved the deployments to Dokku we needed a `composer.lock` anyway.
Thanks for the input though. I am also a fan of including for `composer.lock` for project (as opposed to package) projects

@scheMeZa My apologise that your hard work didnt make it onto master. Thank you still for this PR. 
The similarity of this design compared to the one your brother submitted last year is also not lost on me

**Pull request closed without merging**
