### PR TITLE
Added Bird87ZA's profile

### PR DESCRIPTION
**Pull request by Bird87ZA**
Added my profile

### CODE REVIEW

**Comment by mostertb** [comment]
Hi @Bird87ZA 

Thanks for your submission! You need to instantiate your profile in `\mostertb\PHPSA2018Profiles\Kernel::__construct()` for it to be loaded

**Comment by Bird87ZA** [comment]
Updated, apologies

**Comment by mostertb** [comment]
No worries.

Dont forget to tweet, come say hi and grab a sticker

**Comment by Bird87ZA** [comment]
Already tweeted:
https://twitter.com/A_Scherman/status/1045266671274004485?s=19

Will come get my sticker nownow

**Pull request merged**
