### PR TITLE
Added my profile

### PR DESCRIPTION
**Pull request by WilliamStam**

### CODE REVIEW

**Comment by mostertb** [comment]
Hey @WilliamStam 

Thank you for your submission. It appears that the contents of you submission has not been updated in your Pull Request.

Comment here once you've pushed information about yourself. 

Also make sure  you look at `Step 3` in the instructions

**Comment by mostertb** [comment]
Almost there. 

I like your 'getProfileImageURL()' implementation

You're still missing the stuff from `Step 3` though. You need to instantiate your profile in the kernel for it to be loaded

**Comment by WilliamStam** [comment]
oki it be done... i hope * innocent whistles *

**Comment by mostertb** [comment]
Nicely done 👍 

Dont forget to tweet and come grab a sticker

**Pull request merged**
